@startuml BusinessLogic

package GoogleCloudResources {
class Organization  {
  name: string
  owner: string
  id: string
  }

class Project {
  id:string
  name: string
  owner: string
  select: checkbox
  potentialSavings: number
  }

class Recommendation {
     id: string
      resource: string
      resourceType: string
      description: string
      potentialSavings: number
      select: checkbox
  }
}

class User {
  constructor(emailAddress: string, userName: string,
   profilePicture: string, userID: string, accessToken: string)
  emailAddress: string
      userName: string
      profilePicture: image
      userID: string
      accessToken: string

    }

package Managers {
class ProjectManager <<M>>

class OrganisationManager <<M>>

class RecommendationManager <<M>>
}

User "1"--> OrganisationManager
User "1"--> ProjectManager
User "1"--> RecommendationManager

OrganisationManager "1..*"--> Organization: Manages
ProjectManager "1..*"--> Project: Manages
RecommendationManager "1..*"--> Recommendation: Manages

Organization "0..*" *--> Project: Contains
Project "0..*" *--> Recommendation: Contains

@enduml
